#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=32gb,walltime=05:30:00
#PBS -N app-combine-2d-to-3d

set -e
set -x

axial=`jq -r '.axial' config.json`
coronal=`jq -r '.coronal' config.json`
sagittal=`jq -r '.sagittal' config.json`
TYPE=`jq -r '.type' config.json`

time singularity exec -e docker://renbem/niftymic ./combine.sh ${axial} ${coronal} ${sagittal} ${TYPE}
